services:
  - type: web
    name: stealth-aternos-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SERVER_IP
        value: halfbeak.aternos.host
      - key: SERVER_PORT
        value: '41899'
      - key: BOT_USERNAME
        value: StealthBot_01
